server:
  port: 8080
spring:
  datasource:
    username: RRt9ZPkVul
    password: GuxdAdYpcY
    url: jdbc:mysql://remotemysql.com:3306/RRt9ZPkVul
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform : mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  sql:
    init:
      mode: ALWAYS

